
```{r packages}
#loading packages
library(lubridate)
library(ggplot2)
library(ggmap)
library(ggthemes)
library(dplyr)
library(data.table)
library(tidyverse)
library(shiny)
library(shinydashboard)
library(rgdal)
#maps
library(maps)
theme_set(theme_minimal())
```

```{r rawdatasets}
#loading raw data sets
crash <- read.csv("./data/Crashes_in_DC.csv", stringsAsFactors = FALSE) #all crashes between April 1, 2012 to April 2022
bike_reqs <- read.csv("./data/Vision_Zero_Safety_Bikers.csv", stringsAsFactors = FALSE) #Safety requests shared by bikers
cp_reqs <- read.csv("./data/Vision_Zero_Safety_Cars_Pedestrians.csv", stringsAsFactors = FALSE) #Safety requests shared by pedestrians and drivers
```
```{r cleaningdatasets}
#concatenating requests data sets
reqs <- rbind(bike_reqs, cp_reqs)

#selecting relevant columns
reqs <- reqs %>% select(lat=Y,
                              lon=X,
                              usertype=USERTYPE,
                              rdate=REQUESTDATE,
                              reqtype=REQUESTTYPE,
                              comments=COMMENTS,
)

#formatting date information, adding year and month columns
reqs$rdate <-ymd_hms(reqs$rdate)
reqs$year <-year(reqs$rdate)
reqs$month <-month(reqs$rdate)

#cleaning crash data set
#selecting relevant columns
crash <- crash %>% select(lat=LATITUDE,
                            lon=LONGITUDE,
                            ward=WARD,
                            rdate=REPORTDATE,
                            major_inj=MAJORINJURIES_BICYCLIST,
                            minor_inj=MINORINJURIES_BICYCLIST,
                            unknown_inj=UNKNOWNINJURIES_BICYCLIST,
                            fatal=FATAL_BICYCLIST,
                            total_b=TOTAL_BICYCLES,
                            total_v=TOTAL_VEHICLES,
                            imp_b=BICYCLISTSIMPAIRED,
                            imp_d=DRIVERSIMPAIRED,
                            speeding=SPEEDING_INVOLVED)
#formatting date information, adding year and month columns
crash$rdate <-ymd_hms(crash$rdate)
crash$year <-year(crash$rdate)
crash$month <-month(crash$rdate)

#filtering for incidents from 2011 onwards, that involved at least one bicycle
crash = crash %>% filter(year %in% 2012:2022 & total_b > 0)

#combining dummy injury and fatality variables
for(i in 1:nrow(crash)){
  crash$inj[i] <- NA
  if(crash$minor_inj[i]> 0) { 
    crash$inj[i] <-'Minor Injury'
  } else if (crash$unknown_inj[i] > 0) {
    crash$inj[i] <- 'Unknown Injury'
  }
  else if (crash$major_inj[i]> 0) {
    crash$inj[i] <- 'Major Injury'
  } else if (crash$fatal[i]>0) {
    crash$inj[i] <- 'Fatality'
  }
}
#filtering for incidents of injury
crash = crash %>% filter(inj %in% c("Fatality","Major Injury", "Minor Injury", "Unknown Injury"))

#removing dummy columns
crash <- select(crash, -rdate, -minor_inj, -major_inj, -unknown_inj,)

```

```{r exporting data sets}
#exporting clean requests data to CSV
write.csv(reqs,"./data/bike_reqs_clean.csv", row.names = FALSE)


#exporting clean crash data to csv
write.csv(crash,"./data/crashes_clean.csv", row.names = FALSE)

```

```{r creating map}
dcmap <- get_stamenmap(
  bbox = c(left = -77.225, bottom = 38.84 , right = -76.8125 , top = 39.000),
  maptype = "terrain",
  crop = TRUE,
  color = "color",
  zoom = 12
)

```

```{r viewing map}
dc <- ggmap(dcmap)
```
```{r}
dc
```

```{r making map + viz}
#visualizing safety requests
dc +
  geom_point(data = reqs,
             aes(x = lon,
                 y = lat,
                 color = usertype),
             size = .7) +
  theme_map() +
  theme(legend.background = element_blank(),
        legend.position = "bottom")

```


p + geom_point(aes(x = Longitude, y = Latitude,  colour = Initial.Type.Group), data = i2, size = 0.5) + 
  theme(legend.position="bottom")
  scale_color_viridis_c(option = 'magma')

```{r}
library(DT) #Potentially useful things
library(mapproj)
library(stringi)

```
```{r}
crash %>% count(ward) %>%
  groupby(inj)
```


```{r visualizing injury and fatality}

dc +
  geom_point(data = crash,
             aes(x = lon,
                 y = lat,
                 color = inj),
             size = .7)

```

```{r}
w <- read.csv("./data/Wards_from_2022.csv", stringsAsFactors = TRUE)
```
```{r}
crash %>% count(inj)
```
```{r}
crash = crash %>% filter(inj %in% c("Fatality","Major Injury", "Minor Injury", "Unknown Injury"))
```
```{r}
p <- ggmap(get_googlemap(center = c(lon = -122.335167, lat = 47.608013),
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))

```
```{r}
paris <- get_map(location = "paris")

```

